---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poll-deployment
  namespace: default
  labels:
    app: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poll
  template:
    metadata:
      labels:
        app: poll
    spec:
      containers:
      - name: poll
        image:  epitechcontent/t-dop-600-poll:k8s
        ports:
        - containerPort: 80
        env:
        - name: REDIS_HOST
          value:
      restartPolicy: Always